name: Trigger an event
on: push

jobs:
  build:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatchh
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PAT }}
          repo: Repo02
          owner: Chethan
          event_type: sample_push
  
